### PR TITLE
feat: add support for nested entry

### PR DESCRIPTION
**Pull request by CaiWenlie**
add support for nested entry.
example:
/foo
/foo/bar

### CODE REVIEW

**Comment by IndexXuan** [comment]
Thanks a lot. can you provide example for that ? I cannot test it. you can put on this project /examples/nested

**Comment by CaiWenlie** [comment]
ok, just added a nested page in /examples/vue3-mpa-app

**Comment by IndexXuan** [comment]
Merged and Publish. v1.1.0

**Comment by trivialmonster** [comment]
In /examples/vue3-mpa-app
 /subpage/nested can not visit the right index.html page

**Comment by trivialmonster** [comment]
In /examples/vue3-mpa-app
 /subpage/nested can not visit the right index.html page

**Comment by angus96** [comment]
> 

same here

**Pull request merged**
