### PR TITLE
Add advanced option to create own rewrite rules

### PR DESCRIPTION
**Pull request by sstenn**
Hello! 

At first. Many thanks for this plugin. 
Could you please accept this PR so we can add optional rewrite rules. The changes are very simple and should not interact with existing functionalities.

### CODE REVIEW

**Comment by IndexXuan** [comment]
sorry for late. will publish it soon.

**Comment by IndexXuan** [comment]
v1.1.5.

**Comment by sstenn** [comment]
Can you please check why the npm publish failed? Latest version on npm is v1.1.2

**Comment by IndexXuan** [comment]
@sstenn sorry. I publish to private registry. publish v1.1.3. sorry for that.

**Pull request merged**
